name: hrl 
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pyaml
  - uproot
  - awkward
  - numpy
  - tensorflow>=2.5
  - rich
  - pandas
  - vector
  - numba
  - scipy
  - pandas
  - sklearn
